---
title: "scratchpad"
author: "Ethan Horn, David Lopez"
date: "2023-11-17"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
set.seed(19)
library(lubridate)
library(gghighlight)
library(plotly)
library(ggrepel)
```

# Data Preprocessing

```{r load_data, message=FALSE}
hri.emer.raw          <- jsonlite::fromJSON('datasets/hri_emergencyvisits.json')
hri.hosp.raw          <- jsonlite::fromJSON('datasets/hri_hospitalization.json')
hri.mort.raw          <- jsonlite::fromJSON('datasets/hri_mortality.json')

co2.raw               <- read_csv('datasets/Atmospheric_CO2_Concentrations.csv')

temp.state.raw        <- read_csv('datasets/climdiv_state_year.csv')
temp.state.states     <- read_csv('datasets/model_state.csv')
```
```{r tidy_data}
hri.emer <- hri.emer.raw$tableResult %>%
  filter(hatchingId == -1) %>%  # Filter out "Unstable" points of data
  select(geo, geoId, year, dataValue) %>%
  rename(state           = geo,
         state.id        = geoId,
         emer.per.capita = dataValue) %>%
  mutate(state.id        = as.numeric(state.id),
         year            = as.numeric(year),
         emer.per.capita = as.numeric(emer.per.capita))

hri.hosp <- hri.hosp.raw$tableResult %>%
  filter(hatchingId == -1) %>%  # Filter out "Unstable" points of data
  select(geo, geoId, year, dataValue) %>%
  rename(state           = geo,
         state.id        = geoId,
         hosp.per.capita = dataValue) %>%
  mutate(state.id        = as.numeric(state.id),
         year            = as.numeric(year),
         hosp.per.capita = as.numeric(hosp.per.capita))

hri.mort <- hri.mort.raw$tableResult %>%
  filter(suppressionFlag == 0) %>% # Filter out "Suppressed" points of data
  select(geo, geoId, year, dataValue) %>%
  rename(state             = geo,
         state.id          = geoId,
         mortalities.total = dataValue) %>%
  mutate(state.id          = as.numeric(state.id),
         year              = as.numeric(year),
         mortalities.total = as.numeric(mortalities.total))

co2 <- co2.raw %>%
  filter(Unit == "Parts Per Million") %>%
  select(Date, Value) %>%
  rename(date = Date,
         ppm  = Value) %>%
  mutate(date  = str_replace(date, "M", "-"),
         date  = paste0(date, '-01'),
         date  = as.Date(date),
         year  = lubridate::year(date),
         month = lubridate::month(date))

temp.state <- temp.state.raw %>%
  filter(year >= 2000) %>%
  left_join(temp.state.states, by = join_by(fips)) %>%
  select(year, temp, STUSAB, STATE_NAME, STATE_REGION) %>%
  rename(state.code   = STUSAB,
         state        = STATE_NAME,
         state.region = STATE_REGION)
```

# Exploratory Data Analysis

```{r emer_cor}
hri.emer.model <- lm(emer.per.capita ~ year, data=hri.emer)

ggplot(hri.emer, aes(year, emer.per.capita)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  geom_line(aes(year, emer.per.capita), data = aggregate(emer.per.capita ~ year, hri.emer, mean)) +
  labs(title = "Yearly HRI Emergency Room Visits per Capita by State",
       x     = "Year",
       y     = "Emergency Room visits per Capita (100,000)")

ggplot(hri.emer, aes(factor(year), emer.per.capita)) +
        geom_boxplot() +
        labs(title = "Yearly HRI Emergency Room Visits per Capita by State",
             x     = "Year",
             y     = "Emergency Room visits per Capita (100,000)") +
  scale_x_discrete(guide = guide_axis(angle = 90))

ggplot(hri.emer, aes(factor(year), emer.per.capita)) +
  geom_boxplot(outlier.colour = "red") +
  geom_text_repel(data = hri.emer %>% group_by(year) %>% filter(emer.per.capita > quantile(emer.per.capita, 0.75) + 1.5*IQR(emer.per.capita)), aes(label = state), show.legend = FALSE) +
  labs(title = "Yearly HRI Emergency Room Visits per Capita by State",
       x     = "Year",
       y     = "Emergency Room Visits per Capita (100,000)") +
  scale_x_discrete(guide = guide_axis(angle = 90))

summary(hri.emer.model)
```

```{r hosp_cor}
hri.hosp.model <- lm(hosp.per.capita ~ year, data=hri.hosp)

ggplot(hri.hosp, aes(year, hosp.per.capita)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  geom_line(aes(year, hosp.per.capita), data = aggregate(hosp.per.capita ~ year, hri.hosp, mean)) +
  labs(title = "Yearly HRI Hospitalizations per Capita by State",
       x     = "Year",
       y     = "Hospitalizations per Capita (100,000)")

ggplot(hri.hosp, aes(factor(year), hosp.per.capita)) +
  geom_boxplot() +
  labs(title = "Yearly HRI Hospitalizations per Capita by State",
       x     = "Year",
       y     = "Hospitalizations per Capita (100,000)") +
  scale_x_discrete(guide = guide_axis(angle = 90))

ggplot(hri.hosp, aes(factor(year), hosp.per.capita)) +
  geom_boxplot(outlier.colour = "red") +
  geom_text_repel(data = hri.hosp %>% group_by(year) %>% filter(hosp.per.capita > quantile(hosp.per.capita, 0.75) + 1.5*IQR(hosp.per.capita)), aes(label = state), show.legend = FALSE) +
  labs(title = "Yearly HRI Hospitalizations per Capita by State",
       x     = "Year",
       y     = "Hospitalizations per Capita (100,000)") +
  scale_x_discrete(guide = guide_axis(angle = 90))

summary(hri.hosp.model)
```

```{r mort_cor}
hri.mort.model <- lm(mortalities.total ~ year, data=hri.mort)

ggplot(hri.mort, aes(year, mortalities.total)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(title = "Yearly HRI Mortalities by State",
       x     = "Year",
       y     = "HRI Related Mortalities (Total)")

ggplot(hri.mort, aes(factor(year), mortalities.total)) +
  geom_boxplot() +
  labs(title = "Yearly HRI Mortalities by State",
       x     = "Year",
       y     = "HRI Related Mortalities (Total)") +
  scale_x_discrete(guide = guide_axis(angle = 90))

ggplot(hri.mort, aes(factor(year), mortalities.total)) +
  geom_boxplot(outlier.colour = "red") +
  geom_text_repel(data = hri.mort %>% group_by(year) %>% filter(mortalities.total > quantile(mortalities.total, 0.75) + 1.5*IQR(mortalities.total)), aes(label = state), show.legend = FALSE) +
  labs(title = "Yearly HRI Mortalities by State",
       x     = "Year",
       y     = "HRI Related Mortalities (Total)") +
  scale_x_discrete(guide = guide_axis(angle = 90))

summary(hri.mort.model)
```

```{r temp_cor}
temp.state.model <- lm(temp ~ year, data=temp.state)

ggplot(temp.state, aes(year, temp, fill = state, colour = state.region)) +
        geom_line(show.legend = TRUE) +
        labs(title = "Yearly Average Temperature by State",
             x     = "Year",
             y     = "Mean Yearly Temperature (deg F)",
             colour = "State Region") +
        guides(fill = "none")

ggplot(temp.state, aes(year, temp, fill = state, colour = state)) +
  geom_line(show.legend = FALSE) +
  labs(title = "Yearly Average Temperature by State",
       x     = "Year",
       y     = "Mean Yearly Temperature (deg F)") +
  gghighlight(max(temp) > 67 | min(temp) < 40)


ggplot(temp.state, aes(factor(year), temp)) +
        geom_boxplot() +
        labs(title = "Yearly Average Temperature",
             x     = "Year",
             y     = "Mean Yearly Temperature (deg F)") +
  scale_x_discrete(guide = guide_axis(angle = 90))

summary(temp.state.model)
```

```{r co2_cor}
ggplot(co2, aes(date, ppm)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(title = "Monthly Atmospheric Carbon Dioxide Concentrations (1958 - 2023)",
       x     = "Date",
       y     = "Average Global Atmospheric CO2 Concentration (ppm)")

co2 <- co2 %>% filter(date >= as.Date("2000-01-01"))

co2.model <- lm(ppm ~ date, data= co2)

ggplot(co2, aes(date, ppm)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(title = "Monthly Atmospheric Carbon Dioxide Concentrations (2000 - 2023)",
       x     = "Date",
       y     = "Average Global Atmospheric CO2 Concentration (ppm)")

summary(co2.model)
```

# Simple Linear Regressions

```{r hri-emer-by-co2}
co2.yearly.mean <- co2 %>%
        group_by(year) %>%
        summarise(ppm = mean(ppm))

hri.emer.yearly.mean <- hri.emer %>%
        group_by(year) %>%
        summarise(emer.per.capita = mean(emer.per.capita))

hri.emer.co2 <- hri.emer.yearly.mean %>%
        left_join(co2.yearly.mean, by = join_by(year))

summary(lm(emer.per.capita ~ ppm, data=hri.emer.co2))

ggplot(hri.emer.co2, aes(ppm, emer.per.capita)) +
        geom_point() +
        geom_smooth(method="lm", se=TRUE) +
  labs(title = "Average National HRI Emergency Room Visits by Yearly Average Atmospheric CO2 Concentration",
       x     = "Global Yearly Average Atmospheric CO2 Concentration (ppm)",
       y     = "National US Emergency Room Visits per Capita (100,000) for HRI")
```

```{r hri-hosp-by-co2}
hri.hosp.yearly.mean <- hri.hosp %>%
  group_by(year) %>%
  summarise(hosp.per.capita = mean(hosp.per.capita))

hri.hosp.co2 <- hri.hosp.yearly.mean %>%
  left_join(co2.yearly.mean, by = join_by(year))

summary(lm(hosp.per.capita ~ ppm, data=hri.hosp.co2))

ggplot(hri.hosp.co2, aes(ppm, hosp.per.capita)) +
  geom_point() +
  geom_smooth(method="lm", se=TRUE) +
  labs(title = "Average National HRI Hospitalizations by Yearly Average Atmospheric CO2 Concentration",
       x     = "Global Yearly Average Atmospheric CO2 Concentration (ppm)",
       y     = "National US Hospitalizations per Capita (100,000) for HRI")
```

# Multiple Linear Regressions

```{r emer-by-co2-temp}
hri.emer.co2.temp <- hri.emer.co2 %>%
        left_join(temp.state)

hri.emer.co2.temp.model <- lm(emer.per.capita ~ ppm + temp, data = hri.emer.co2.temp)

summary(hri.emer.co2.temp.model)
```

```{r hosp-by-co2-temp}
hri.hosp.co2.temp <- hri.hosp.co2 %>%
        left_join(temp.state)

hri.hosp.co2.temp.model <- lm(hosp.per.capita ~ ppm + temp, data = hri.hosp.co2.temp)

summary(hri.hosp.co2.temp.model)
```